// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfny8Pls6RG5G9urBOQf_5XE4JXnbfBtI',
    appId: '1:122290970923:web:db068d7a7324f6a3b1e56e',
    messagingSenderId: '122290970923',
    projectId: 'chat-app-8bdae',
    authDomain: 'chat-app-8bdae.firebaseapp.com',
    storageBucket: 'chat-app-8bdae.firebasestorage.app',
    measurementId: 'G-63WFNRND08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Z3qJwzsFivV3zJqMpSU_OYAijzRo_10',
    appId: '1:122290970923:android:f91e3f166e661fedb1e56e',
    messagingSenderId: '122290970923',
    projectId: 'chat-app-8bdae',
    storageBucket: 'chat-app-8bdae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC837QXYPzxHkEegh47CMG4QCpj4_EWVOM',
    appId: '1:122290970923:ios:35bc7ca8f6e43167b1e56e',
    messagingSenderId: '122290970923',
    projectId: 'chat-app-8bdae',
    storageBucket: 'chat-app-8bdae.firebasestorage.app',
    iosClientId: '122290970923-9oejmu38flpr3i0kmdh2iatn98cku654.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC837QXYPzxHkEegh47CMG4QCpj4_EWVOM',
    appId: '1:122290970923:ios:35bc7ca8f6e43167b1e56e',
    messagingSenderId: '122290970923',
    projectId: 'chat-app-8bdae',
    storageBucket: 'chat-app-8bdae.firebasestorage.app',
    iosClientId: '122290970923-9oejmu38flpr3i0kmdh2iatn98cku654.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfny8Pls6RG5G9urBOQf_5XE4JXnbfBtI',
    appId: '1:122290970923:web:d9e4663c2d767ab5b1e56e',
    messagingSenderId: '122290970923',
    projectId: 'chat-app-8bdae',
    authDomain: 'chat-app-8bdae.firebaseapp.com',
    storageBucket: 'chat-app-8bdae.firebasestorage.app',
    measurementId: 'G-E09ZNV8W7T',
  );
}
